### ISSUE TITLE
Add a readme + license

### ISSUE THREAD

**Issue by michaelboyles** [caseyscarborough/wanikani-api#1]
Seems neat. I was considering writing something like this for my own use. Could you add a readme that answers the below questions?

What license is it available under? What's a hello world example of making a request? Is the library published anywhere if I want to depend on it?

**Comment by caseyscarborough** [comment]
Hey @michaelboyles, thanks for pointing that out, I definitely should've added those. I would certainly license it as MIT.

For now, here's the basic usage if you want to use it in your project:

Add JitPack to your build.gradle with the dependency:

```groovy
repositories {
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'com.github.caseyscarborough:wanikani-api:master'
}
```

Then you can use the API like this:

```java
// Create a client with your API token
WaniKaniClient client = new WaniKaniClient("my-api-token");

// Basic methods use a simple format like the following
Summary summary = client.getSummary();

// Some others API methods require a request body, but the requests all use a
// builder format so you can easily see the parameters the request takes.

// Here's how to get all level 60 Kanji:
SubjectsRequest request = SubjectsRequest.builder()
    .addType(SubjectType.KANJI)
    .levels(60)
    .build();
List<Subject> subjects = client.getSubjects(request);
```

You can find all the implemented functions [here](https://github.com/caseyscarborough/wanikani-api/blob/master/src/main/java/com/wanikani/api/v2/WaniKaniClient.java#L25-L95) (or just use autocomplete in your IDE on your `client` instance).

Here are some caveats though:

-  I created this library when the V2 API was still in Beta, so the API may have changed a bit (I just tested it and the "SRS Stages" API seems to have been removed, so that method doesn't work, but the rest seem fine).
- Not all V2 API methods are implemented but most basic functionality is there.

I will work on adding a README and LICENSE, but in the meantime please feel free to let me know if you have any questions or if something specific you need doesn't work or hasn't been implemented, and I can fix/add it (but PRs are also welcome).

**Comment by caseyscarborough** [comment]
@michaelboyles I added the README and LICENSE as well as an additional example to handle pagination. Hope this helps!

**Comment by michaelboyles** [comment]
Thanks so much for the quick reply. I'll take a look in the next few days. I'll have a go at addressing those issues you opened too. They seem simple enough.
